"use strict";
const n1 = 16;
const n2 = 2;
const n3 = 4;
const n4 = 4;
let sum, mul, div;
sum = n3 + n4;
mul = n2 * n4;
div = n1 / n2;
console.log(`Here the result of sum: ${sum}\nHere the result of multiply: ${mul} \nHere the result of division: ${div}`);
