"use strict";
const line1 = "________";
const line2 = "________";
const line3 = "________";
const line4 = "________";
console.log(line1 + line2 + line3 + line4);
console.log("Here the number 8 appearing");
console.log(5 + 3);
console.log(10 - 2);
console.log(2 * 4);
console.log(16 / 2);
